/CaTS/random/randomSeed 123456
/CaTS/random/saveSeed false
/CaTS/RootIO/Filename pi-_5GeV_hits.root
/CaTS/Analysis/Filename pi-_5GeV_analysis.root
# low time slices
/CaTS/SensitiveDetectors/TimeSliceSizeLow 0.025 ns
/CaTS/SensitiveDetectors/MinTimeLow 0. ns
/CaTS/SensitiveDetectors/MaxTimeLow 5. ns
# medium time slices
/CaTS/SensitiveDetectors/TimeSliceSizeMed 0.5 ns
/CaTS/SensitiveDetectors/MinTimeMed 0. ns
/CaTS/SensitiveDetectors/MaxTimeMed 100. ns
# high time slices
/CaTS/SensitiveDetectors/TimeSliceSizeHig 50 ns
/CaTS/SensitiveDetectors/MinTimeHig 0. ns
/CaTS/SensitiveDetectors/MaxTimeHig 5000. ns
# Shoot along various directions
#/tracking/verbose 1
/gun/direction 0. 0. 1.
/gun/position 0. 0. 0. mm
/gun/particle pi-
/gun/energy 5 GeV
/run/beamOn 10
exit
