/CaTS/random/randomSeed JOB
/CaTS/random/saveSeed false
/CaTS/RootIO/Filename PARTICLE_ENERGYGeV_hits_JOB.root
/CaTS/Analysis/Filename PARTICLE_ENERGYGeV_analysis_JOB.root
# low time slices
/CaTS/SensitiveDetectors/TimeSliceSizeLow 0.025 ns
/CaTS/SensitiveDetectors/MinTimeLow 0. ns
/CaTS/SensitiveDetectors/MaxTimeLow 5. ns
# medium time slices
/CaTS/SensitiveDetectors/TimeSliceSizeMed 0.5 ns
/CaTS/SensitiveDetectors/MinTimeMed 0. ns
/CaTS/SensitiveDetectors/MaxTimeMed 100. ns
# high time slices
/CaTS/SensitiveDetectors/TimeSliceSizeHig 50 ns
/CaTS/SensitiveDetectors/MinTimeHig 0. ns
/CaTS/SensitiveDetectors/MaxTimeHig 5000. ns
# Shoot along various directions
#/tracking/verbose 1
/gun/direction 0. 0. 1.
/gun/position 0. 0. 0. mm
/gun/particle PARTICLE
/gun/energy ENERGY GeV
/run/beamOn NEVTS
exit
