void resp (){
  const Int_t n1= 6;
  Double_t Ein[n1]= {1.0,2.0,5.0,10.0,20.0,50.0};  
  Double_t Einerr[n1]={0.001,0.001,0.001,0.001,0.001,0.001};
  Double_t Evis_ap[n1]={2.339,3.242,5.901,10.32,19.11,45.92};
  Double_t Evisrms_ap[n1]={0.2306,0.2622,0.383,0.5671,0.9332,1.774};
  Double_t Evis_p[n1]={0.8269,1.631,4.079,8.391,17.22,44.12};
  Double_t Evisrms_p[n1]={0.1184,0.1839,0.3645,0.5237,0.7951,1.504};
  Double_t Evis_n[n1]={0.7458,1.539,3.94,8.179,16.95,43.78};
  Double_t Evisrms_n[n1]={0.1191,0.2019,0.4016,0.5794,0.8836,1.631};
  Double_t Evis_kp[n1]={1.131,1.973,4.536,8.944,17.81,45.04};
  Double_t Evisrms_kp[n1]={0.1854,0.2474,0.4105,0.6603,1.343,2.943};
  Double_t Evis_km[n1]={1.16,2.004,4.55,9.028,17.98,45.21};
  Double_t Evisrms_km[n1]={0.1896,0.2391,0.4078,0.7254,1.168,2.288};
  Double_t Evis_pim[n1]={0.932,1.727,4.283,8.773,17.83,45.38};
  Double_t Evisrms_pim[n1]={0.1336,0.2061,0.3954,0.5758,0.9109,1.872};
  Double_t Evis_pip[n1]={0.8906,1.691,4.213,8.657,17.71,45.09};
  Double_t Evisrms_pip[n1]={0.1577,0.2375,0.4131,0.6335,1.003,1.982};
  Double_t Evis_em[n1]={0.9922,1.984,4.962,9.927,19.86,49.66};
  Double_t Evisrms_em[n1]={0.01098,0.01368,0.02308,0.03224,0.05164,0.09118};
  //
  Double_t Evis_ap_rel[n1];
  Double_t Evisrms_ap_rel[n1];
  Double_t Evis_p_rel[n1];
  Double_t Evisrms_p_rel[n1];
  Double_t Evis_n_rel[n1];
  Double_t Evisrms_n_rel[n1];
  Double_t Evis_kp_rel[n1];
  Double_t Evisrms_kp_rel[n1];
  Double_t Evis_km_rel[n1];
  Double_t Evisrms_km_rel[n1];
  Double_t Evis_pim_rel[n1];
  Double_t Evisrms_pim_rel[n1];
  Double_t Evis_pip_rel[n1];
  Double_t Evisrms_pip_rel[n1];
  Double_t Evis_em_rel[n1];
  Double_t Evisrms_em_rel[n1];
  for (unsigned int i=0;i<n1;i++)
    {
        Evis_ap_rel[i]=Evis_ap[i]/Ein[i];
	Evisrms_ap_rel[i]=Evisrms_ap[i]/Ein[i];
	Evis_p_rel[i]=Evis_p[i]/Ein[i];
	Evisrms_p_rel[i]=Evisrms_p[i]/Ein[i];
	Evis_n_rel[i]=Evis_n[i]/Ein[i];
	Evisrms_n_rel[i]=Evisrms_n[i]/Ein[i];
	Evis_kp_rel[i]=Evis_kp[i]/Ein[i];
	Evisrms_kp_rel[i]=Evisrms_kp[i]/Ein[i];
	Evis_km_rel[i]=Evis_km[i]/Ein[i];
	Evisrms_km_rel[i]=Evisrms_km[i]/Ein[i];
	Evis_pim_rel[i]=Evis_pim[i]/Ein[i];
	Evisrms_pim_rel[i]=Evisrms_pim[i]/Ein[i];
	Evis_pip_rel[i]=Evis_pip[i]/Ein[i];
	Evisrms_pip_rel[i]=Evisrms_pip[i]/Ein[i];
	Evis_em_rel[i]=Evis_em[i]/Ein[i];
	Evisrms_em_rel[i]=Evisrms_em[i]/Ein[i]; 
    }
  TCanvas *c = new TCanvas("c", "response", 200, 10, 1000, 800);
  TGraphErrors *gr_ref = new TGraphErrors(n1,Ein,Ein,Einerr,Einerr);
  gr_ref->SetLineColor(1);
  gr_ref->SetLineWidth(1);
  gr_ref->SetLineStyle(2);
  gr_ref->SetMarkerColor(3);
  gr_ref->SetMarkerStyle(1);
  gr_ref->SetMarkerSize(1.2);
  gr_ref->SetTitle("visible Energy");
  gr_ref->SetName("visible Energy");
  gr_ref->GetXaxis()->SetTitle("Ein [GeV]");
  gr_ref->GetYaxis()->SetTitle("Evis. [GeV]");
  gr_ref->Draw("ACP");
  TGraphErrors *gr_em = new TGraphErrors(n1,Ein,Evis_em,Einerr,Evisrms_em);
  gr_em->SetLineColor(4);
  gr_em->SetLineWidth(1);
  gr_em->SetMarkerColor(4);
  gr_em->SetMarkerStyle(20);
  gr_em->SetMarkerSize(1.2);
  gr_em->Draw("CP");
  TGraphErrors *gr_pim = new TGraphErrors(n1,Ein,Evis_pim,Einerr,Evisrms_pim);
  gr_pim->SetLineColor(7);
  gr_pim->SetLineWidth(1);
  gr_pim->SetMarkerColor(7);
  gr_pim->SetMarkerStyle(20);
  gr_pim->SetMarkerSize(1.2);
  gr_pim->Draw("CP");
  TGraphErrors *gr_pip = new TGraphErrors(n1,Ein,Evis_pip,Einerr,Evisrms_pip);
  gr_pip->SetLineColor(15);
  gr_pip->SetLineWidth(1);
  gr_pip->SetMarkerColor(15);
  gr_pip->SetMarkerStyle(21);
  gr_pip->SetMarkerSize(1.2);
  gr_pip->Draw("CP");
  TGraphErrors *gr_ap = new TGraphErrors(n1,Ein,Evis_ap,Einerr,Evisrms_ap);
  gr_ap->SetLineColor(3);
  gr_ap->SetLineWidth(1);
  gr_ap->SetMarkerColor(3);
  gr_ap->SetMarkerStyle(21);
  gr_ap->SetMarkerSize(1.2);
  gr_ap->Draw("CP");
  //TFitResultPtr fitpt_p=gr_ap->Fit("pol1","S");
  TGraphErrors *gr_p = new TGraphErrors(n1,Ein,Evis_p,Einerr,Evisrms_p);
  gr_p->SetLineColor(4);
  gr_p->SetLineWidth(1);
  gr_p->SetMarkerColor(4);
  gr_p->SetMarkerStyle(22);
  gr_p->SetMarkerSize(1.2);
  gr_p->Draw("CP");
  TGraphErrors *gr_n = new TGraphErrors(n1,Ein,Evis_n,Einerr,Evisrms_n);
  gr_n->SetLineColor(2);
  gr_n->SetLineWidth(1);
  gr_n->SetMarkerColor(2);
  gr_n->SetMarkerStyle(20);
  gr_n->SetMarkerSize(1.2);
  gr_n->Draw("CP");
  TGraphErrors *gr_km = new TGraphErrors(n1,Ein,Evis_km,Einerr,Evisrms_km);
  gr_km->SetLineColor(9);
  gr_km->SetLineWidth(1);
  gr_km->SetMarkerColor(9);
  gr_km->SetMarkerStyle(23);
  gr_km->SetMarkerSize(1.2);
  gr_km->Draw("CP");
  TGraphErrors *gr_kp = new TGraphErrors(n1,Ein,Evis_kp,Einerr,Evisrms_kp);
  gr_kp->SetLineColor(6);
  gr_kp->SetLineWidth(1);
  gr_kp->SetMarkerColor(6);
  gr_kp->SetMarkerStyle(21);
  gr_kp->SetMarkerSize(1.2);
  gr_kp->Draw("CP");
  TLegend *legend = new TLegend(.6, .15, 0.85, .4);
  legend->AddEntry(gr_ref, "reference");
  legend->AddEntry(gr_em, "e^{-}");
  legend->AddEntry(gr_pim, "#pi^{-}");
  legend->AddEntry(gr_ap, "anti proton");
  legend->AddEntry(gr_p, "proton");
  legend->AddEntry(gr_n, "neutron");
  legend->AddEntry(gr_km, "K^{-}");
  legend->AddEntry(gr_kp, "K^{+}");
  legend->Draw();

  TCanvas *c2 = new TCanvas("c2", "relative response", 200, 10, 1000, 800);
  TMultiGraph *mg = new TMultiGraph();
  mg->SetMinimum(0.5);
  mg->SetMaximum(2.5);
  mg->SetTitle("relative Energy response;Ein [GeV];Evis/Ein");
  c2->SetGrid();
  TGraphErrors *gr_rel_em = new TGraphErrors(n1,Ein,Evis_em_rel,Einerr,Evisrms_em_rel);
  gr_rel_em->SetLineColor(4);
  gr_rel_em->SetLineWidth(1);
  gr_rel_em->SetMarkerColor(4);
  gr_rel_em->SetMarkerStyle(20);
  gr_rel_em->GetYaxis()->SetLimits(0.,2.5);
  gr_rel_em->SetTitle("e^{-}");
  mg->Add( gr_rel_em);
  TGraphErrors *gr_rel_pim = new TGraphErrors(n1,Ein,Evis_pim_rel,Einerr,Evisrms_pim_rel);
  gr_rel_pim->SetLineColor(7);
  gr_rel_pim->SetLineWidth(1);
  gr_rel_pim->SetMarkerColor(7);
  gr_rel_pim->SetMarkerStyle(20);
  gr_rel_pim->SetTitle("#pi^{-}");
  mg->Add( gr_rel_pim);
  TGraphErrors *gr_rel_pip = new TGraphErrors(n1,Ein,Evis_pip_rel,Einerr,Evisrms_pip_rel);
  gr_rel_pip->SetLineColor(15);
  gr_rel_pip->SetLineWidth(1);
  gr_rel_pip->SetMarkerColor(15);
  gr_rel_pip->SetMarkerStyle(21);
  gr_rel_pip->SetTitle("#pi^{+}");
  mg->Add( gr_rel_pip);
  TGraphErrors *gr_rel_ap = new TGraphErrors(n1,Ein,Evis_ap_rel,Einerr,Evisrms_ap_rel);
  gr_rel_ap->SetLineColor(3);
  gr_rel_ap->SetLineWidth(1);
  gr_rel_ap->SetMarkerColor(3);
  gr_rel_ap->SetMarkerStyle(21);
  gr_rel_ap->SetTitle("antiproton");
  mg->Add( gr_rel_ap);
  TGraphErrors *gr_rel_p = new TGraphErrors(n1,Ein,Evis_p_rel,Einerr,Evisrms_p_rel);
  gr_rel_p->SetLineColor(4);
  gr_rel_p->SetLineWidth(1);
  gr_rel_p->SetMarkerColor(4);
  gr_rel_p->SetMarkerStyle(22);
  gr_rel_p->SetTitle("proton");
  mg->Add( gr_rel_p);
  TGraphErrors *gr_rel_n = new TGraphErrors(n1,Ein,Evis_n_rel,Einerr,Evisrms_n_rel);
  gr_rel_n->SetLineColor(2);
  gr_rel_n->SetLineWidth(1);
  gr_rel_n->SetMarkerColor(2);
  gr_rel_n->SetMarkerStyle(20);
  gr_rel_n->SetTitle("neutron");
  mg->Add( gr_rel_n);
  TGraphErrors *gr_rel_km = new TGraphErrors(n1,Ein,Evis_km_rel,Einerr,Evisrms_km_rel);
  gr_rel_km->SetLineColor(9);
  gr_rel_km->SetLineWidth(1);
  gr_rel_km->SetMarkerColor(9);
  gr_rel_km->SetMarkerStyle(23);
  gr_rel_km->SetTitle("K^{-}");
  mg->Add( gr_rel_km);
  TGraphErrors *gr_rel_kp = new TGraphErrors(n1,Ein,Evis_kp_rel,Einerr,Evisrms_kp_rel);
  gr_rel_kp->SetLineColor(6);
  gr_rel_kp->SetLineWidth(1);
  gr_rel_kp->SetMarkerColor(6);
  gr_rel_kp->SetMarkerStyle(21);
  gr_rel_kp->SetTitle("K^{+}");
  mg->Add( gr_rel_kp);
  mg->SetMaximum(2.4);
  mg->SetMinimum(0.6);
  mg->Draw("apl");
  TLegend *leg = c2->BuildLegend(.6, .6, 0.85, .85);
  leg->Draw();
  pave = new TPaveText(2,2.2,30,2.4);
  pave->SetTextAlign(12);
  pave->AddText("Material: PbF2, Physics List: FTFPBERT");
  pave->Draw();
}
